### ISSUE TITLE
Invalid slashes in summary generated on Windows

### ISSUE THREAD

**Issue by eugene-goroschenya** [imfly/gitbook-summary#13]
The 'book sm' generates summary with invalid slashes (**\\**) in links, on GitHub it must be forward slashes (**/**).

The #10 doesn't fix the problem

**Comment by eugene-goroschenya** [comment]
@imfly, could you publish new version of package to the registry?
Then I will close the issue.

**Comment by imfly** [comment]
:ok:

**Comment by eugene-goroschenya** [comment]
Thanks a lot!
