### ISSUE TITLE
Feature request --「 ignore title 」

### ISSUE THREAD

**Issue by TianYongwei** [imfly/gitbook-summary#30]
Feature request --「 ignore title 」
---
Cool tool ! "gitbook-summary" helps me a lot. Thanks ！

book.json file is useful, help me shorten my command line.

Recently,  I want to remove the 'title' from my blog's navigation (note.tianyongwei.com).
but likely gitbook-summary can't do it.

I try modify the source code ,and found this:
```Javascript

var root,
      title, // todo: don`t use `name`?
      outputFile,
      catalog,
      ignores,
      unchanged,
...
```

is the feature (don`t use `name`)  a todo feature?

**Comment by imfly** [comment]
Yes, can`t use the `name` sometime, welcome you fix it and give a pr 😄

**Comment by TianYongwei** [comment]
Good idea, I will try.
