### ISSUE TITLE
Does not hidden the node_modules and _book folders

### ISSUE THREAD

**Issue by jaingmengmeng** [imfly/gitbook-summary#31]
It does not hidden the node_modules and _book folders.
I found a bug in gitbook-summary\lib\summary\index.js
![bug](https://note.youdao.com/yws/public/resource/35f71a832434259055392642e19b06e3/xmlnote/47BB36DDCC814322A7C1A8C9014D358B/6992)

**Comment by jaingmengmeng** [comment]
The strings in front of test functions should not have quotes

**Comment by imfly** [comment]
Yes, fine,  you are right. 👍
