### ISSUE TITLE
If directory name has a whitespace between words, markdown is broken

### ISSUE THREAD

**Issue by ekinbarut** [imfly/gitbook-summary#37]
Sample: 

**Actual**: [Inbound Marketing](Basics/Inbound Marketing/README.md)
**Expected**: [Inbound Marketing](Basics/Inbound%20Marketing/README.md)

Whitespaces in directory names should be replaced with `%20` to get a working link

**Comment by imfly** [comment]
Yes, you are welcome to submit a PR to fix this problem.

**Comment by ekinbarut** [comment]
@imfly would you be able to publish the updated package on npmjs? I'm planning to use the CLI tool in a CI pipeline.

**Comment by imfly** [comment]
Published  👌  @ekinbarut

**Comment by goasleep** [comment]
Would you like to tell me which version has this pr？seem version 1.2.4 still has this problem.

**Comment by casionone** [comment]
> Would you like to tell me which version has this pr？seem version 1.2.4 still has this problem.

same problem @imfly
