### ISSUE TITLE
Gulp Task

### ISSUE THREAD

**Issue by lisaluescher** [imfly/gitbook-summary#4]
Hi,
Can you please help me with building a gulp task for the automization of the summary file?

**Comment by imfly** [comment]
Hi, @lisaluescher 

Tt`s easy.

Firstly, install gitbook-summay in your project, for example:

```
npm install gitbook-summary --save-dev
```

Then, copy the follow codes to your `gulpfile.js`

```
var summary = require('gitbook-summary/lib/').summary;

gulp.task('summary', function() {
    // If you have no book.json, please add other options.
    var options = {
        root: "."
    };

    return summary(options);
});
```

You can run the task:

```
gulp summary
```

**Comment by lisaluescher** [comment]
Thank you so much!
It worked perfectly :)
