### ISSUE TITLE
意外生成多余的Pages目录

### ISSUE THREAD

**Issue by cyio** [imfly/gitbook-summary#5]
如图，这个Pages不知是从哪来的，我本地还有你的程序里都没这个，很奇怪
刚开始没装Gitbook时是没有这个问题的

![](http://ww1.sinaimg.cn/large/4e5d3ea7jw1f3ow0wfo2aj20dk0cymyr.jpg)

这个是book.json

![](http://ww3.sinaimg.cn/large/4e5d3ea7jw1f3ovxe6z5xj20mu04yt9u.jpg)

**Comment by imfly** [comment]
gitbook  是哪个版本，看内容好像是gitbook生成的，你把它放在"ignores"里直接忽略就行了

**Comment by cyio** [comment]
这个是运行`book sm`命令后产生的问题，我本地没有Pages目录，所以也没法排除（试着写上，没有用）
gitbook刚装所以是最新的

**Comment by imfly** [comment]
我反复试验了下，无法重现你的问题。我使用的gitbook-summary是1.0.14（最新发布版），以及1.0.33（开发版），都没有出现你的问题。也验证了gitbook 2.0.1, 2.6.7(最新发布版）,3.0.1.pre.13（最新预览版）。

gitbook-summary仅仅对现有文件夹下的文件做处理，summary.md是它产生的唯一文件，中间没有任何其他写操作。

从你的截图可以知道，pages的内容是_book的一部分，是gitbook在构建过程中产生的，你再检查一下是不是运行了某个任务，产生了这些内容。

谢谢你的反馈

**Comment by cyio** [comment]
在另一台电脑，没复现，暂关闭。
