### ISSUE TITLE
含有短杠的文件名格式化

### ISSUE THREAD

**Issue by cyio** [imfly/gitbook-summary#6]
比如这样的文件名`this-is-filename`，第一个短杠前的词 this 会被忽略掉

**Comment by imfly** [comment]
默认会对`-`拆分处理，把第一个拆分的当作数字进行排序了。这个问题好处理。。。

**Comment by imfly** [comment]
在对章节的排序中，默认使用 `1-this-is-filenname` 或者 `a-this-is-filename`的形式，也就是加上`序号-`作为排序标志。

我想最好是提供一个选项参数，让用户选择是否进行排序处理，或者选择排序模式（使用数字排序，还是字母排序）。

像你这种情况，默认不进行人工排序或数字排序，就不会有问题，选择字母排序就会出现这种情况，把`this-`作为排序字母序列了。
